### PR TITLE
Backport changes from production UI to cloud (aka new) UI

### PR DESCRIPTION
**Pull request by mojavelinux**
This PR backports changes added to production UI and build since the cloud UI was forked from it. Except for a few minor style changes, this does not fundamentally change the appearance or behavior of the cloud UI. Once this is merged, the cloud UI will become the official new UI.

### CODE REVIEW

**Comment by amarantha-k** [comment]
@mojavelinux PR#16 & #17 look good and are ready to be merged. Just confirming that I can merge them before this PR

**Comment by mojavelinux** [comment]
Yep, go ahead and merge.

**Comment by mojavelinux** [comment]
I'll rebase this PR.

**Comment by mojavelinux** [comment]
Rebase complete.

**Pull request merged**
